In [1]:
!pip install -q -U watermark

In [2]:
import math
import sys, os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import warnings
warnings.filterwarnings('ignore')

In [3]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

### Carregando os Dados

In [4]:
lista_labels_valores_ausentes = ['n/a', 'na', 'undefined']

In [5]:
df_dsa = pd.read_csv('dataset.csv', na_values= lista_labels_valores_ausentes)

In [6]:
df_dsa.shape

(150001, 55)

In [7]:
df_dsa.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [8]:
pd.set_option('display.max_rows', 100)

In [9]:
df_dsa.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [10]:
dicionario = pd.read_excel('dicionario.xlsx')

In [11]:
dicionario.shape

(56, 2)

In [12]:
dicionario.head(10)

          Fields                                        Description
0      bearer id                             xDr session identifier
1      Dur. (ms)                  Total Duration of the xDR (in ms)
2          Start      Start time of the xDR (first frame timestamp)
3       Start ms  Milliseconds offset of start time for the xDR ...
4            End         End time of the xDR (last frame timestamp)
5         End ms  Milliseconds offset of end time of the xDR (la...
6       Dur. (s)                   Total Duration of the xDR (in s)
7           IMSI           International Mobile Subscriber Identity
8  MSISDN/Number  MS International PSTN/ISDN Number of mobile - ...
9           IMEI            International Mobile Equipment Identity

In [13]:
pd.set_option('display.max_colwidth', 100)

In [14]:
dicionario.head(60)

,Fields,Description
0,bearer id,xDr session identifier
1,Dur. (ms),Total Duration of the xDR (in ms)
2,Start,Start time of the xDR (first frame timestamp)
3,Start ms,Milliseconds offset of start time for the xDR (first frame timestamp)
4,End,End time of the xDR (last frame timestamp)
5,End ms,Milliseconds offset of end time of the xDR (last frame timestamp)
6,Dur. (s),Total Duration of the xDR (in s)
7,IMSI,International Mobile Subscriber Identity
8,MSISDN/Number,MS International PSTN/ISDN Number of mobile - customer number
9,IMEI,International Mobile Equipment Identity
10,Last Location Name,User location call name (2G/3G/4G) at the end of the bearer
11,Avg RTT DL (ms),Average Round Trip Time measurement Downlink direction (msecond)
12,Avg RTT UL (ms),Average Round Trip Time measurement Uplink direction (msecond)
13,Avg Bearer TP DL (kbps),Average Bearer Throughput for Downlink (kbps) - based on BDR duration
14,Avg Bearer TP UL (kbps),Average Bearer Throughput for uplink (kbps) - based on BDR duration
15,TCP DL Retrans. Vol (Bytes),TCP volume of Downlink packets detected as retransmitted (bytes)
16,TCP UL Retrans. Vol (Bytes),TCP volume of Uplink packets detected as retransmitted (bytes)
17,DL TP < 50 Kbps (%),Duration ratio when Bearer Downlink Throughput < â€¦.
18,50 Kbps < DL TP < 250 Kbps (%),Duration ratio when Bearer Downlink Throughput range is â€¦
19,250 Kbps < DL TP < 1 Mbps (%),Duration ratio when Bearer Downlink Throughput range is â€¦
20,DL TP > 1 Mbps (%),Duration ratio when Bearer Downlink Throughput > â€¦.
21,UL TP < 10 Kbps (%),Duration ratio when Bearer Uplink Throughput < â€¦.
22,10 Kbps < UL TP < 50 Kbps (%),Duration ratio when Bearer Uplink Throughput range is â€¦
23,50 Kbps < UL TP < 300 Kbps (%),Duration ratio when Bearer Uplink Throughput range is â€¦
24,UL TP > 300 Kbps (%),Duration ratio when Bearer Uplink Throughput > â€¦.
25,HTTP DL (Bytes),HTTP data volume (in Bytes) received by the MS during this session
26,HTTP UL (Bytes),HTTP data volume (in Bytes) sent by the MS during this session
27,Activity Duration DL (ms),Activity Duration for downlink (ms) - excluding periods of inactivity > 500 ms
28,Activity Duration UL (ms),Activity Duration for uplink (ms) - excluding periods of inactivity > 500 ms
29,Dur. (ms).1,Total Duration of the xDR (in ms)
30,Handset Manufacturer,Handset manufacturer
31,Handset Type,Handset type of the mobile device
32,Nb of sec with 125000B < Vol DL,Number of seconds with IP Volume DL >
33,Nb of sec with 1250B < Vol UL < 6250B,Number of seconds with IP Volume UL between â€¦
34,Nb of sec with 31250B < Vol DL < 125000B,Number of seconds with IP Volume DL between â€¦
35,Nb of sec with 37500B < Vol UL,Number of seconds with IP Volume UL >
36,Nb of sec with 6250B < Vol DL < 31250B,Number of seconds with IP Volume DL between â€¦
37,Nb of sec with 6250B < Vol UL < 37500B,Number of seconds with IP Volume UL between â€¦
38,Nb of sec with Vol DL < 6250B,Number of seconds with IP Volume DL <
39,Nb of sec with Vol UL < 1250B,Number of seconds with IP Volume UL <
40,Social Media DL (Bytes),Social Media data volume (in Bytes) received by the MS during this session
41,Social Media UL (Bytes),Social Media data volume (in Bytes) sent by the MS during this session
42,YouTube DL (Bytes),YouTube data volume (in Bytes) received by the MS during this session
43,YouTube UL (Bytes),YouTube data volume (in Bytes) sent by the MS during this session
44,Netflix DL (Bytes),Netflix data volume (in Bytes) received by the MS during this session
45,Netflix UL (Bytes),Netflix data volume (in Bytes) sent by the MS during this session
46,Google DL (Bytes),Google data volume (in Bytes) Received by the MS during this session
47,Google UL (Bytes),Google data volume (in Bytes) sent by the MS during this session
48,Email DL (Bytes),Email data volume (in Bytes) Received by the MS during this session
49,Email UL (Bytes),Email data volume (in Bytes) sent by the MS during this session
50,Gaming DL (Bytes),Gaming data volume (in Bytes) Received by the MS during this session
51,Gaming UL (Bytes),Gaming data volume (in Bytes) sent by the MS during this session
52,Other DL,Other data volume (in Bytes) received by the MS during this session
53,Other UL,Other data volume (in Bytes) sent by the MS during this session
54,Total DL (Bytes),Data volume (in Bytes) received by the MS during this session (IP layer + overhead)
55,Total UL (Bytes),Data volume (in Bytes) sent by the MS during this session (IP layer + overhead)

## AnÃ¡lise ExploratÃ³ria

In [15]:
df_dsa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      140442 non-null  object
 30  Handset Type                              140442 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

In [16]:
df_dsa.describe(include=object)

,Start,End,Last Location Name,Handset Manufacturer,Handset Type
count,150000,150000,148848,140442,140442
unique,9997,6403,45547,169,1395
top,4/26/2019 7:25,4/25/2019 0:01,D41377B,Apple,Huawei B528S-23A
freq,203,1150,80,59565,19752

In [17]:
df_compara_colunas = pd.concat([pd.Series(df_dsa.columns.tolist()), dicionario['Fields']], axis = 1)

In [18]:
df_compara_colunas.rename(columns = {0: 'Coluna no Dataset', 'Fields': 'Coluna no Dicionario'}, inplace = True)

In [19]:
df_compara_colunas

,Coluna no Dataset,Coluna no Dicionario
0,Bearer Id,bearer id
1,Start,Dur. (ms)
2,Start ms,Start
3,End,Start ms
4,End ms,End
5,Dur. (ms),End ms
6,IMSI,Dur. (s)
7,MSISDN/Number,IMSI
8,IMEI,MSISDN/Number
9,Last Location Name,IMEI
10,Avg RTT DL (ms),Last Location Name
11,Avg RTT UL (ms),Avg RTT DL (ms)
12,Avg Bearer TP DL (kbps),Avg RTT UL (ms)
13,Avg Bearer TP UL (kbps),Avg Bearer TP DL (kbps)
14,TCP DL Retrans. Vol (Bytes),Avg Bearer TP UL (kbps)
15,TCP UL Retrans. Vol (Bytes),TCP DL Retrans. Vol (Bytes)
16,DL TP < 50 Kbps (%),TCP UL Retrans. Vol (Bytes)
17,50 Kbps < DL TP < 250 Kbps (%),DL TP < 50 Kbps (%)
18,250 Kbps < DL TP < 1 Mbps (%),50 Kbps < DL TP < 250 Kbps (%)
19,DL TP > 1 Mbps (%),250 Kbps < DL TP < 1 Mbps (%)
20,UL TP < 10 Kbps (%),DL TP > 1 Mbps (%)
21,10 Kbps < UL TP < 50 Kbps (%),UL TP < 10 Kbps (%)
22,50 Kbps < UL TP < 300 Kbps (%),10 Kbps < UL TP < 50 Kbps (%)
23,UL TP > 300 Kbps (%),50 Kbps < UL TP < 300 Kbps (%)
24,HTTP DL (Bytes),UL TP > 300 Kbps (%)
25,HTTP UL (Bytes),HTTP DL (Bytes)
26,Activity Duration DL (ms),HTTP UL (Bytes)
27,Activity Duration UL (ms),Activity Duration DL (ms)
28,Dur. (ms).1,Activity Duration UL (ms)
29,Handset Manufacturer,Dur. (ms).1
30,Handset Type,Handset Manufacturer
31,Nb of sec with 125000B < Vol DL,Handset Type
32,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 125000B < Vol DL
33,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 1250B < Vol UL < 6250B
34,Nb of sec with 37500B < Vol UL,Nb of sec with 31250B < Vol DL < 125000B
35,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 37500B < Vol UL
36,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with 6250B < Vol DL < 31250B
37,Nb of sec with Vol DL < 6250B,Nb of sec with 6250B < Vol UL < 37500B
38,Nb of sec with Vol UL < 1250B,Nb of sec with Vol DL < 6250B
39,Social Media DL (Bytes),Nb of sec with Vol UL < 1250B
40,Social Media UL (Bytes),Social Media DL (Bytes)
41,Google DL (Bytes),Social Media UL (Bytes)
42,Google UL (Bytes),YouTube DL (Bytes)
43,Email DL (Bytes),YouTube UL (Bytes)
44,Email UL (Bytes),Netflix DL (Bytes)
45,Youtube DL (Bytes),Netflix UL (Bytes)
46,Youtube UL (Bytes),Google DL (Bytes)
47,Netflix DL (Bytes),Google UL (Bytes)
48,Netflix UL (Bytes),Email DL (Bytes)
49,Gaming DL (Bytes),Email UL (Bytes)
50,Gaming UL (Bytes),Gaming DL (Bytes)
51,Other DL (Bytes),Gaming UL (Bytes)
52,Other UL (Bytes),Other DL
53,Total UL (Bytes),Other UL
54,Total DL (Bytes),Total DL (Bytes)
55,NaN,Total UL (Bytes)

In [20]:
df_dsa[['Dur. (ms)', 'Dur. (ms).1']]

        Dur. (ms)   Dur. (ms).1
0       1823652.0  1.823653e+09
1       1365104.0  1.365104e+09
2       1361762.0  1.361763e+09
3       1321509.0  1.321510e+09
4       1089009.0  1.089009e+09
...           ...           ...
149996    81230.0  8.123076e+07
149997    97970.0  9.797070e+07
149998    98249.0  9.824953e+07
149999    97910.0  9.791063e+07
150000        NaN           NaN

[150001 rows x 2 columns]

In [21]:
df_dsa.rename(columns = {'Dur. (ms)': 'Dur (s)',
                              'Dur. (ms).1': 'Dur (ms)',
                              'Start ms': 'Start offset (ms)',
                              'End ms': 'End Offset (ms)'},
                   inplace = True)

In [22]:
 pd.concat([pd.Series(df_dsa.columns.tolist()), dicionario['Fields']], axis = 1)

,0,Fields
0,Bearer Id,bearer id
1,Start,Dur. (ms)
2,Start offset (ms),Start
3,End,Start ms
4,End Offset (ms),End
5,Dur (s),End ms
6,IMSI,Dur. (s)
7,MSISDN/Number,IMSI
8,IMEI,MSISDN/Number
9,Last Location Name,IMEI
10,Avg RTT DL (ms),Last Location Name
11,Avg RTT UL (ms),Avg RTT DL (ms)
12,Avg Bearer TP DL (kbps),Avg RTT UL (ms)
13,Avg Bearer TP UL (kbps),Avg Bearer TP DL (kbps)
14,TCP DL Retrans. Vol (Bytes),Avg Bearer TP UL (kbps)
15,TCP UL Retrans. Vol (Bytes),TCP DL Retrans. Vol (Bytes)
16,DL TP < 50 Kbps (%),TCP UL Retrans. Vol (Bytes)
17,50 Kbps < DL TP < 250 Kbps (%),DL TP < 50 Kbps (%)
18,250 Kbps < DL TP < 1 Mbps (%),50 Kbps < DL TP < 250 Kbps (%)
19,DL TP > 1 Mbps (%),250 Kbps < DL TP < 1 Mbps (%)
20,UL TP < 10 Kbps (%),DL TP > 1 Mbps (%)
21,10 Kbps < UL TP < 50 Kbps (%),UL TP < 10 Kbps (%)
22,50 Kbps < UL TP < 300 Kbps (%),10 Kbps < UL TP < 50 Kbps (%)
23,UL TP > 300 Kbps (%),50 Kbps < UL TP < 300 Kbps (%)
24,HTTP DL (Bytes),UL TP > 300 Kbps (%)
25,HTTP UL (Bytes),HTTP DL (Bytes)
26,Activity Duration DL (ms),HTTP UL (Bytes)
27,Activity Duration UL (ms),Activity Duration DL (ms)
28,Dur (ms),Activity Duration UL (ms)
29,Handset Manufacturer,Dur. (ms).1
30,Handset Type,Handset Manufacturer
31,Nb of sec with 125000B < Vol DL,Handset Type
32,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 125000B < Vol DL
33,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 1250B < Vol UL < 6250B
34,Nb of sec with 37500B < Vol UL,Nb of sec with 31250B < Vol DL < 125000B
35,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 37500B < Vol UL
36,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with 6250B < Vol DL < 31250B
37,Nb of sec with Vol DL < 6250B,Nb of sec with 6250B < Vol UL < 37500B
38,Nb of sec with Vol UL < 1250B,Nb of sec with Vol DL < 6250B
39,Social Media DL (Bytes),Nb of sec with Vol UL < 1250B
40,Social Media UL (Bytes),Social Media DL (Bytes)
41,Google DL (Bytes),Social Media UL (Bytes)
42,Google UL (Bytes),YouTube DL (Bytes)
43,Email DL (Bytes),YouTube UL (Bytes)
44,Email UL (Bytes),Netflix DL (Bytes)
45,Youtube DL (Bytes),Netflix UL (Bytes)
46,Youtube UL (Bytes),Google DL (Bytes)
47,Netflix DL (Bytes),Google UL (Bytes)
48,Netflix UL (Bytes),Email DL (Bytes)
49,Gaming DL (Bytes),Email UL (Bytes)
50,Gaming UL (Bytes),Gaming DL (Bytes)
51,Other DL (Bytes),Gaming UL (Bytes)
52,Other UL (Bytes),Other DL
53,Total UL (Bytes),Other UL
54,Total DL (Bytes),Total DL (Bytes)
55,NaN,Total UL (Bytes)

### Etapa 1 - Tratamento de Valores Ausentes
#### 1 - Identificando Valores Ausentes
#### 2 - Drop de Colunas
#### 3 - ImputaÃ§Ã£o com Preenchimento
#### 4 - ImputaÃ§Ã£o com Preenchimento Progressivo
#### 5 - ImputaÃ§Ã£o de VariÃ¡veis CategÃ³ricas
#### 6 - Drop de Linhas

#### 1.1 - Identificando Valores Ausentes

In [23]:
def func_percent_valores_ausentes(df):
    totalCells = np.product(df.shape)
    
    missingCount = df.isnull().sum()

    totalMissing = missingCount.sum()

    print("O dataset tem", round(((totalMissing/totalCells) * 100), 2), '%', 'de valores ausentes.')

In [26]:
func_percent_valores_ausentes(df_dsa)

O dataset tem 12.72 % de valores ausentes.

In [27]:
def func_percent_valores_ausentes_coluna(df):
    #Valores Ausentes
    mis_val = df.isnull().sum()
    
    #Porcentagem de valores ausentes
    mis_val_percent = 100 * mis_val / len(df)
    
    #Tipo de dados das colunas com valores ausentes
    mis_val_dtype = df.dtypes

    #Cria um tabela com os resultados
    mis_val_table = pd.concat([mis_val, mis_val_percent, mis_val_dtype], axis = 1)

    #Renomear as colunas
    mis_val_table_renomeada = mis_val_table.rename(
    columns = {0: 'Valores ausentes', 1: '% de Valores Ausentes', 2: 'Dtype'})

    #Classifica a tabela por porcentagem de valores ausentes de forma decrescente e remove colunas sem valores  faltantes
    mis_val_table_renomeada = mis_val_table_renomeada[mis_val_table_renomeada.iloc[:,0] != 0].sort_values('% de Valores Ausentes', ascending = False).round(2)

    print("O dataset tem " + str(df.shape[1]) + " colunas.\n"
        "Encontrado: " + str(mis_val_table_renomeada.shape[0]) + " colunas que tÃªm valores ausentes.")

    if mis_val_table_renomeada.shape[0] == 0:
        return

    return mis_val_table_renomeada

In [28]:
mis_val = df_dsa.isnull().sum()
mis_val_percent = 100 * mis_val / len(df_dsa)
mis_val_dtype = df_dsa.dtypes

In [29]:
table = pd.concat([mis_val, mis_val_percent, mis_val_dtype], axis = 1)
table.rename(columns = {0: "Valores ausentes", 1: '%', 2: 'Dtype'}, inplace = True)

In [30]:
df_missing = func_percent_valores_ausentes_coluna(df_dsa)

O dataset tem 55 colunas.
Encontrado: 41 colunas que tÃªm valores ausentes.

## 1.2 Drop de Colunas

In [31]:
colunas_para_remover = df_missing[df_missing['% de Valores Ausentes'] >= 30.00].index.tolist()

In [32]:
colunas_para_remover

['Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with 125000B < Vol DL',
 'TCP UL Retrans. Vol (Bytes)',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'TCP DL Retrans. Vol (Bytes)',
 'HTTP UL (Bytes)',
 'HTTP DL (Bytes)']

In [33]:
colunas_para_remover = [col for col in colunas_para_remover if col not in ['TCP UL Retrans. Vol (Bytes)',
                                                                           'TCP DL Retrans. Vol (Bytes)']]

In [34]:
colunas_para_remover

['Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'HTTP UL (Bytes)',
 'HTTP DL (Bytes)']

In [35]:
df_dsa_limpo = df_dsa.drop(colunas_para_remover, axis = 1)

In [36]:
df_dsa_limpo.shape

(150001, 47)

In [38]:
func_percent_valores_ausentes(df_dsa_limpo)

O dataset tem 3.85 % de valores ausentes.

In [39]:
func_percent_valores_ausentes_coluna(df_dsa_limpo)

O dataset tem 47 colunas.
Encontrado: 33 colunas que tÃªm valores ausentes.

,Valores ausentes,% de Valores Ausentes,Dtype
TCP UL Retrans. Vol (Bytes),96649,64.43,float64
TCP DL Retrans. Vol (Bytes),88146,58.76,float64
Avg RTT DL (ms),27829,18.55,float64
Avg RTT UL (ms),27812,18.54,float64
Handset Type,9559,6.37,object
Handset Manufacturer,9559,6.37,object
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
IMEI,572,0.38,float64
IMSI,570,0.38,float64
Start,1,0.00,object
Avg Bearer TP UL (kbps),1,0.00,float64
Avg Bearer TP DL (kbps),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Dur (ms),1,0.00,float64
Dur (s),1,0.00,float64
End Offset (ms),1,0.00,float64
End,1,0.00,object
Start offset (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Total DL (Bytes),1,0.00,float64

### 1.3 ImputaÃ§Ã£o com Preenchimento Reverso

In [40]:
# ImputaÃ§Ã£o de valores ausentes usando backward fill
# method = 'bfill': Bfill ou backward-fill propaga o primeiro valor nÃ£o nulo observado para trÃ¡s atÃ© que 
# outro valor nÃ£o nulo seja encontrado.
def func_dsa_bfill(df, col):
    count = df[col].isna().sum()

    df[col] = df[col].fillna(method = 'bfill')

    print(f'{count} valores ausentes na coluna {col} foram substituÃ­dos usando o mÃ©todo de preenchimento reverso.')

In [41]:
func_dsa_bfill(df_dsa_limpo, "TCP UL Retrans. Vol (Bytes)")

96649 valores ausentes na coluna TCP UL Retrans. Vol (Bytes) foram substituÃ­dos usando o mÃ©todo de preenchimento reverso.

In [42]:
func_dsa_bfill(df_dsa_limpo, "TCP DL Retrans. Vol (Bytes)")

88146 valores ausentes na coluna TCP DL Retrans. Vol (Bytes) foram substituÃ­dos usando o mÃ©todo de preenchimento reverso.

## ImputaÃ§Ã£o com Preenchimento Progressivo

In [43]:
func_percent_valores_ausentes_coluna(df_dsa_limpo)

O dataset tem 47 colunas.
Encontrado: 33 colunas que tÃªm valores ausentes.

,Valores ausentes,% de Valores Ausentes,Dtype
Avg RTT DL (ms),27829,18.55,float64
Avg RTT UL (ms),27812,18.54,float64
Handset Type,9559,6.37,object
Handset Manufacturer,9559,6.37,object
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
IMEI,572,0.38,float64
IMSI,570,0.38,float64
TCP UL Retrans. Vol (Bytes),5,0.00,float64
TCP DL Retrans. Vol (Bytes),5,0.00,float64
Start,1,0.00,object
Avg Bearer TP UL (kbps),1,0.00,float64
Avg Bearer TP DL (kbps),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Dur (ms),1,0.00,float64
Dur (s),1,0.00,float64
End Offset (ms),1,0.00,float64
End,1,0.00,object
Start offset (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Total DL (Bytes),1,0.00,float64

##### Avg RTT DL (ms) e Avg RTT UL (ms) tÃªm as prÃ³ximas porcentagens mais altas de valores ausentes com cerca de 18,% cada. Vamos verificar se as variÃ¡veis estÃ£o enviesadas (nÃ£o seguem uma distribuiÃ§Ã£o normal) usando o mÃ©todo skw(), que retorna o coeficiente de assimetria.

In [47]:
#Analisando com mÃ©todo skew()
df_dsa_limpo['Avg RTT DL (ms)'].skew(skipna = True)

62.90782807995961

In [53]:
# Analisando com Shapiro-wilk
from scipy import stats

#Extraindo a sÃ©rie "AVG"
AVG = df_dsa_limpo['Avg RTT DL (ms)'].dropna()

#Aplique o teste de Shapiro-Wilk
stat, p_valor = stats.shapiro(AVG)

print(f'EstatÃ­stica de teste: {stat}')
print(f'Valor-p: {p_valor}')

# Verifique a hipÃ³tese nula com base no p-valor
alfa = 0.05 # NÃ­vel de significÃ¢ncia

if p_valor > alfa:
    print("NÃ£o hÃ¡ evidÃªncias para rejeitar a hipÃ³tese nula (os dados parecem seguir uma distribuiÃ§Ã£o normal).")
else:
    print("A hipÃ³tese nula Ã© rejeitada (os dados nÃ£o seguem uma distribuiÃ§Ã£o normal).")

EstatÃ­stica de teste: 0.07621683677471347
Valor-p: 2.1189776770041153e-187
A hipÃ³tese nula Ã© rejeitada (os dados nÃ£o seguem uma distribuiÃ§Ã£o normal).

In [45]:
df_dsa_limpo['Avg RTT UL (ms)'].skew(skipna = True)

28.45741458546382

In [54]:
# # Analisando com Shapiro-wilk
from scipy import stats

#Extraindo a sÃ©rie "AVG"
AVG = df_dsa_limpo['Avg RTT UL (ms)'].dropna()

#Aplique o teste de Shapiro-Wilk
stat, p_valor = stats.shapiro(AVG)

print(f'EstatÃ­stica de teste: {stat}')
print(f'Valor-p: {p_valor}')

# Verifique a hipÃ³tese nula com base no p-valor
alfa = 0.05 # NÃ­vel de significÃ¢ncia

if p_valor > alfa:
    print("NÃ£o hÃ¡ evidÃªncias para rejeitar a hipÃ³tese nula (os dados parecem seguir uma distribuiÃ§Ã£o normal).")
else:
    print("A hipÃ³tese nula Ã© rejeitada (os dados nÃ£o seguem uma distribuiÃ§Ã£o normal).")

EstatÃ­stica de teste: 0.12112014441627172
Valor-p: 1.2407118431892299e-185
A hipÃ³tese nula Ã© rejeitada (os dados nÃ£o seguem uma distribuiÃ§Ã£o normal).

#### Se a simetria estiver entre -0,5 e 0,5, os dados sÃ£o bastante simÃ©tricos
#### Se a assimetria estiver entre -1 e -0,5 ou entre 0,5 e 1, os dados estÃ£o moderadamente inclinados
#### Se a assimetria for menor que -1 ou maior que 1, os dados estÃ£o altamente enviesados

#### Visto que ambas as colunas sÃ£o fortemente enviesadas positivamente Ã© aconselhÃ¡vel nÃ£o imputÃ¡-las com sua mÃ©dia.
#### Portanto, usaremos o preenchimento progressivo.

In [56]:
def func_dsa_ffil(df, col):

    count = df[col].isna().sum()

    df[col] = df[col].fillna(method = 'ffill')

    print(f'{count} valores ausentes na coluna {col} foram substituÃ­dos usando o mÃ©todo de preenchimento progressivo.')

In [57]:
func_dsa_ffil(df_dsa_limpo, 'Avg RTT DL (ms)')

27829 valores ausentes na coluna Avg RTT DL (ms) foram substituÃ­dos usando o mÃ©todo de preenchimento progressivo.

In [58]:
func_dsa_ffil(df_dsa_limpo, 'Avg RTT UL (ms)')

27812 valores ausentes na coluna Avg RTT UL (ms) foram substituÃ­dos usando o mÃ©todo de preenchimento progressivo.

In [59]:
func_percent_valores_ausentes(df_dsa_limpo)

O dataset tem 0.44 % de valores ausentes.

In [60]:
func_percent_valores_ausentes_coluna(df_dsa_limpo)

O dataset tem 47 colunas.
Encontrado: 31 colunas que tÃªm valores ausentes.

,Valores ausentes,% de Valores Ausentes,Dtype
Handset Type,9559,6.37,object
Handset Manufacturer,9559,6.37,object
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
IMEI,572,0.38,float64
IMSI,570,0.38,float64
TCP UL Retrans. Vol (Bytes),5,0.00,float64
TCP DL Retrans. Vol (Bytes),5,0.00,float64
Start,1,0.00,object
Avg Bearer TP UL (kbps),1,0.00,float64
Avg Bearer TP DL (kbps),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Dur (ms),1,0.00,float64
Dur (s),1,0.00,float64
End Offset (ms),1,0.00,float64
End,1,0.00,object
Start offset (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Total DL (Bytes),1,0.00,float64

#### Visto que "Handset Type" e "Handset Manufacturer" sÃ£o colunas categÃ³ricas, Ã© melhor imputÃ¡-las com o valor "unknown" para que nÃ£o enviesemos os dados

In [62]:
# Preenche valor NA
def func_preencher_valor_NA_categorico(df, col, value):
    count = df[col].isna().sum()

    df[col] = df[col].fillna(value)

    if type(value) == 'str':
        print(f'{count} valores ausentes na coluna {col} foram substituÃ­dos por "{value}".')
    else:
        print(f'{count} valores ausentes na coluna {col} foram substituÃ­dos por {value}.')

In [63]:
func_preencher_valor_NA_categorico(df_dsa_limpo, 'Handset Type', 'unknown')
func_preencher_valor_NA_categorico(df_dsa_limpo, 'Handset Manufacturer', 'unknown')

9559 valores ausentes na coluna Handset Type foram substituÃ­dos por unknown.
9559 valores ausentes na coluna Handset Manufacturer foram substituÃ­dos por unknown.

In [64]:
func_percent_valores_ausentes(df_dsa_limpo)

O dataset tem 0.17 % de valores ausentes.

In [65]:
func_percent_valores_ausentes_coluna(df_dsa_limpo)

O dataset tem 47 colunas.
Encontrado: 29 colunas que tÃªm valores ausentes.

,Valores ausentes,% de Valores Ausentes,Dtype
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
IMEI,572,0.38,float64
IMSI,570,0.38,float64
TCP UL Retrans. Vol (Bytes),5,0.00,float64
TCP DL Retrans. Vol (Bytes),5,0.00,float64
Start,1,0.00,object
Avg Bearer TP UL (kbps),1,0.00,float64
Avg Bearer TP DL (kbps),1,0.00,float64
Dur (s),1,0.00,float64
End Offset (ms),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Dur (ms),1,0.00,float64
End,1,0.00,object
Start offset (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Total DL (Bytes),1,0.00,float64

In [66]:
def func_dsa_drop_linhas_com_na(df):

    old = df.shape[0]

    df.dropna(inplace = True)

    new = df.shape[0]

    count = old - new

    print(f'{count} linhas contendo valores ausentes foram descartadas.')

In [67]:
func_dsa_drop_linhas_com_na(df_dsa_limpo)

3114 linhas contendo valores ausentes foram descartadas.

In [68]:
func_percent_valores_ausentes(df_dsa_limpo)

O dataset tem 0.0 % de valores ausentes.

In [69]:
df_dsa_limpo.to_csv('df_dsa_limpo.csv')